### PR TITLE
Fix simple typo in python function higlighting & improve highlighting of c/cpp struct/class members.

### PR DESCRIPTION
**Pull request by roflcopter4**
This tiny little pull request makes two changes.

1. I noticed that python functions were not being highlighted. Methods were, just not normal functions. After a quick glance at the source I saw that it was trying to link the non-existent "PythonFunction" group to Function rather than the correct "PythonFunctionTag". I fixed this typo and now everything is fine.
2. This change is a bit more dubious. It always bothered me that struct members would be blindly highlighted wherever they appeared, regardless of whether they were in any way part of a struct instance. For example every single instance of the word 'buf' would be highlighted if I were foolish enough to make that part of a struct. This made me basically not use this feature at all - I found it that annoying. Finally I decided to do something about it and originally made a simple change so that it now only ever highlights these after '.' or '->', which solves the problem, though it now does not highlight them in the original definition of the struct.

Again, the first change is pretty minor. Unless something was quite odd with my setup it should be a fix for everyone. The second change is not so obvious, I consider it an improvement, but that may be personal.

EDIT: When I wrote this thing at 4:30 am last night I couldn't make the prefix mechanism work for whatever reason, so I resorted to hackishly adding a second regex and arbitrary checks in the python source. Looking back, I easily got the system working and moved the changes to a new prefix for cMembers and cppMembers in their ".vim" files, which works just fine. I should really do these things _before_ I make pull requests. Oh well. With this commit, the python source is untouched, only the three ".vim" files are slightly changed.

### CODE REVIEW

**Comment by c0r73x** [comment]
Ah nice, it looks good. But maybe the prefix stuff should be optional.

Anyway I will merge the PR and we can add an option for the prefix stuff if people wants it :)

**Comment by roflcopter4** [comment]
Argh, I was just a few minutes too late. What strange timing. I only now just noticed that my solution for highlighting only after periods and arrows wasn't working when they appeared after a closing ']' (as in, array[i]->member). It seems Vim doesn't consider that to be the end of a word. I added one last commit (5 minutes too late) that fixes this. If you do add the feature I recommend merging that commit too.

That aside, I'm happy to see this get merged, and I do agree that it makes sense as an option. In my opinion the member highlighting feature is more annoying than useful when it highlights things that aren't members, but that might possibly just be me. It bugged me with easytags for years. Again though, it probably makes the most sense as an option.

EDIT: It seems I'm even more of a git noob than I thought. Would I have to make another pull request to merge that little change? Seems a little excessive. The only change was
```
--- a/plugin/neotags/c.vim
+++ b/plugin/neotags/c.vim
@@ -10,7 +10,7 @@ let g:neotags#c#c = {
 let g:neotags#c#m = {
             \   'group': 'cMemberTag',
             \   'ignore': '(__anon[0-9a-f]+|[_\w]+::)',
-            \   'prefix': '\%(\>\%(\.\|->\)\)\@<='
+            \   'prefix': '\%(\%(\>\|\]\)\%(\.\|->\)\)\@<='
             \ }
```
and the same for the cpp.vim file. Like I said above, if you do want to add this as an option then this little fix would improve it a fair bit.

**Comment by c0r73x** [comment]
Oh, sorry for being so fast :p I will merge the last commit as well ;)

**Comment by roflcopter4** [comment]
And thirdly (and now I feel like a bit of a fool) I just noticed that I accidentally merged my 'tags' file that was generated when working on that file... you might want to remove that too. Sorry about that.

**Comment by c0r73x** [comment]
Hehe no problem, I should have added that to gitignore anyway :p 

Humm I reverted the commit but now I can't merge this pr, maybe you need to make a new pr?

**Comment by c0r73x** [comment]
Now it should be merged. Not sure why github was acting this way. I guess it's because I havn't had my coffee yet.

**Comment by roflcopter4** [comment]
Sometimes I wonder whether the world would continue functioning if somehow all the coffee on earth disappeared. Chaos.

Anyway I'm glad that got sorted out. Incidentally, I'm pretty sure the Python typo fix solves [this issue](https://github.com/c0r73x/neotags.nvim/issues/21). Looks like that guy was having the same problem.

**Pull request merged**
