### PR TITLE
Increase performance, organize tags files, add features and options

### PR DESCRIPTION
**Pull request by roflcopter4**
Hi again. I've been obsessively tweaking and messing with this plugin over the past few weeks, and ended up making quite a few changes. I don't necessarily expect this pull request to be accepted but I do at least think some of the things are worth discussing. There are a few different kinds of changes I made here.

1.  Style changes: the most dubious. I wound up fiddling with the python file quite a bit and changed parts of it to a style I prefer. I probably shouldn't have done this - if it bugs you at all then I could go back and try to undo this wherever possible. This mainly involves things like the number of blank lines in a function and how continuation lines are indented.

2.  Minor: added a few things to .gitignore that could be useful. I don't know about you, but I often seem to have core files pop up all over the place rather inexplicably.

3.  Made further changes to C syntax highlighting. I added another check for a closing `)` in member highlighting after noticing that wasn't working either (just like `]` wasn't working earlier). I also added a check to functions so that they are only highlighted when used as such (ie with an immediately following opening `(` character). These changes might have a bit of a performance impact, but I haven't seen much difference with them one way or the other. Regardless, I tried to mitigate it by limiting the number of lookback characters to 5.

4.  On to the more major changes. I got sick of having tags files all over the place and decided to find a way to keep them all together. I therefore added the vim option `g:neotags_directory`, which defaults to `~/.vim_tags`, and spent a surprisingly long time trying to get the plugin to properly store tags files there. After much fiddling and failure it now seems to work. The full base path of the file being edited (ie the directory it's in) is used, with path separators substituted with `__`. In Windows the drive letter is substituted similarly. For example, a file `~/foo/bar.c` would have a tags file called `__home__baz__foo.tags`, and in Windows a file `C:\My    Documents\mystuff\windows_sux.cpp` would be `C____My Documents__mystuff.tags`. Note the four underscores after the drive letter. The spaces shouldn't be a problem either - everything is quoted where required.

Probably the largest changes are in how tags are processed. The first time I opened up a very large project with this plugin (EFL, a huge library), the performance was so awful that it was actually impossible to even do as much as scroll. nvim was truly unusable. EFL has probably in the many thousands of flags and they were nearly all being sent to the editor to cope with at once - this is just too much. I tried to do a few things to fix this.

5.  In the old easytags plugin, the majority of tags were highlighted as syntax keywords wherever it was possible. This is (at least supposed to be) faster than using regex matches. In some of the comments of the easytags plugin the author mentioned that he planned to add the keywords feature to the python translation but never got around to it. I went ahead and did this. Now, whenever tag groups do not have a unique prefix or suffix specified they are given to nvim as keywords.

6.  This change I'm not really sure about, but I didn't see why keyword matches needed to be supplied any 'notin' information, so I removed that. Frankly I'm not sure what that accomplished at all, so if I'm missing something here it should be easy to add back.

7.  The biggest difference was made by trying to selectively pass only useful tags to neovim. Mine might not be an ideal solution, but I tried to do this by reading the whole contents of the current buffer into a python string (yuck) and comparing each and every tag, one by one, to that string. If the tag isn't in the file, it is rejected. This is slow, but has the benefit of being done in the background. The editor is fully usable while this processing takes place, and when it is done the list of things to highlight will be vastly smaller than it would have been otherwise.
This changed the experience of editing a file in the EFL source tree from impossible to *mostly* smooth. Things still chug a bit now and then, but it is practically buttery smooth compared to what it was previously. For small projects the processing is almost instantaneous and shouldn't be a noticeable difference. For large ones, it can take a long time. If normal cpython is used it might be as bad as 30+ seconds. If pypy is used it is more like 5-10 seconds. Pypy is highly recommended.

8.  Added the ability to specify a project root directory. If recursion is enabled and the current directory is inside a project root, ctags will always target the project root instead of the current file. This not only grabs all of the project's tags but makes sure that there is only one tags file for the project, not a whole bunch that largely duplicate each other. This is available through two new ex commands `NeotagsAddProject` and `NeotagsRemoveProject`. Each takes one required argument (I really ought to allow no argument to be entered instead use the current directory) which is converted to an absolute path, checked for existence, and appended to a file called `g:neotags_directory/neotags.txt`.

I also added a few further Vim options.

1.  `g:neotags_norecurse_dirs` is a list of directories in which recursion should not be done even if recursion is enabled. It defaults to what I think is a sensible list including the home directory, /usr/share, /usr/include, and other such directories where recursion is probably neither wanted nor helpful. Only the edited file will be passed to ctags if it appears in one of these directories.

2.  `g:neotags_ignored_tags` is a list of possible tags that should never be highlighted. It's empty by default because it requires that every tag be compared against every item in the list, which ain't fast. I find it useful in C to stop the plugin from highlighting things like `NULL` or `BUFSIZ`, etc, that are technically preprocessor macros but already have coloring.

3.  `g:neotags_no_autoconf` is a simple boolean which, if enabled, adds `--exclude` flags to the ctags argument list for all standard autoconf files. This keeps the tag files a fair bit smaller, and thus makes the processing faster. Most people have no use for the tags in these files anyway, so I set this option to 1 by default.

Sorry for such a long explanation. I figured that I changed enough things that I really ought to explain how and why.

### CODE REVIEW

**Comment by c0r73x** [comment]
This sounds like a nice PR, I was actually thinking about using keywords when I wrote the plugin but I couldn't find a good way to do it. And more performance is always a good thing 😊 

I will test your fork at work on monday and if it works well I will merge it 😉

**Comment by c0r73x** [comment]
Hi, I've found some issues with the fork. 

If i set ```neotags_recursive = 0``` it throws an error:

```
error caught while executing async callback:
UnboundLocalError("local variable 'recurse' referenced before assignment",)
Traceback (most recent call last):
  File "/home/uscpe/dotfiles/vim/.vim/bundle/neotags.nvim/rplugin/python3/neotags/neotags.py", line 163, in highlight

    self.__groups[ft] = self._parseTags(ft)
  File "/home/uscpe/dotfiles/vim/.vim/bundle/neotags.nvim/rplugin/python3/neotags/neotags.py", line 252, in _parseTag
s
    self._get_file()
  File "/home/uscpe/dotfiles/vim/.vim/bundle/neotags.nvim/rplugin/python3/neotags/neotags.py", line 624, in _get_file

    if recurse:
UnboundLocalError: local variable 'recurse' referenced before assignment
 
the call was requested at
  File "/home/uscpe/.local/lib64/python3.5/site-packages/neovim/api/nvim.py", line 170, in filter_notification_cb
    notification_cb(name, args)
  File "/home/uscpe/.local/lib64/python3.5/site-packages/neovim/plugin/host.py", line 107, in _on_notification
    handler(*args)
  File "/home/uscpe/.local/lib64/python3.5/site-packages/neovim/plugin/host.py", line 69, in _wrap_function
    return fn(*args)
  File "/home/uscpe/dotfiles/vim/.vim/bundle/neotags.nvim/rplugin/python3/neotags/__init__.py", line 25, in highlight

    self.__vim.async_call(self.__neotags.highlight, False)
```

Also it seems you have removed the variable ```appendpath``` which removes the ability to run applications like the_silver_searcher to find the files that it should build tags for (like this ```let g:neotags_ctags_bin = 'ag -g "" ' .  getcwd() . ' | ctags'```). This is useful for using agignore to ignore for example .git dirs and other directories you want as global ignore and not specify them in multiple files, also it's faster than letting ctags find the files because of multithreads.

And because you have changed some variables, and added others the documentation is incorrect.

Other than that it looks nice, I can really see that it is faster with your fork. I tested it in the neovim source and before it was very sluggish, but now I can't feel any difference against running neotags on or off :+1: 

*Edit:*
I did found something else which is a bit strange, it seems that order isn't respected anymore also it seems that it's case insensitive? I have a class in typescript called Ajax, with a function called ajax. And both get highlighted as the function. Which is wrong in both ways, because the classes have higher priority and Ajax is not the same as ajax so it shouldn't be highlighted by that rule.

**Comment by roflcopter4** [comment]
I knew there had to be bugs I missed. I somewhat absentmindedly changed and removed some of the things I didn't really understand/see the purpose of, such as the appendpath you mentioned. Fortunately it shouldn't be terribly difficult to remedy. 

I fixed the exception. I didn't remove the `neotagsrecursive` variable, I just moved it to a different function and clearly forgot to assign a value to `recurse` when the former is false. I never envisioned that someone would ever use a plugin like this without recursion enabled so I didn't even think to test it.

I added (yet another) vim option to support external find tools. The `neotags_find_tool` variable, if set and recursion is enabled, will be automatically joined with the ctags binary name in a pipeline. The command line for ctags is also altered to remove the unnecessary -R flag and the path name. That way it only receives the files sent to it from the specified tool. Both ag's and ctags' file exclusion methods can be combined this way, which in my cursory testing seems to work quite well.

I haven't even the slightest clue why there would be case or priority issues. I didn't change anything that ought to affect that. Things are most certainly case sensitive in all the languages I've tested (which, to be fair. is only C, python, perl, shell, and vim). That issue is bizarre. Could it have something to do with keyword highlighting? Maybe restricted to that language? I'm not sure where to look.

**Comment by c0r73x** [comment]
No problem, ```neotags_find_tool``` is probably a better name for the variable anyway :p 

Humm it's odd about the highlights, I will check if it's only in the javascript/typescript files that this happends or if it's in C/C++ aswell.

**Comment by c0r73x** [comment]
Humm it's odd, it look as it should in C/C++ but not in js or python.

C++: https://goo.gl/6VLENv
Python: https://goo.gl/vzupP8

*Edit:*
I spoke to soon, there is some strangeness in C++ as well https://goo.gl/AB3XW2 . As you can see the class name is not highlighted :/

**Comment by roflcopter4** [comment]
I'm a bit at a loss to explain this. There are maybe a couple of possibilities.
1. Some kind of shenanigans with keyword highlighting.
2. Something is horribly awry with my key ignoring logic.
3. Maybe files aren't being updated properly??
4. The gods are angry???

I tried removing all keyword highlighting entirely. Everything I've tested personally seems to be working. I know I have linked a few categories to custom highlighting groups in my .vimrc but those are linked to standard ones elsewhere. I'm curious to know if things magically work after reverting to match higlighting.

For what it's worth, these are my own settings:
```
    let g:neotags_enabled = 1
    let g:neotags_highlight = 1
    let g:neotags_run_ctags = 1
    let g:neotags_verbose = 1
    let g:neotags_recursive = 1
    let g:neotags_no_autoconf = 1
    let g:neotags_find_tool = 'ag -g ""'

    let g:neotags#c#order = 'cgstuedfpm'
    let g:neotags#cpp#order = 'cgstuedfpm'

    " C
    highlight def link cEnumTag Enum
    highlight def link cMemberTag CMember
    highlight def link cPreProcTag PreProc
    highlight def link cFunctionTag CFuncTag

    " C++
    highlight def link cppEnumTag Enum
    highlight def link cppMemberTag CMember
    highlight def link cppPreProcTag PreProc
    highlight def link cppFunctionTag CFuncTag

    " Sh
    highlight def link shFunctionTag CFuncTag
    highlight def link shAliasTag Constant

    " Perl
    highlight def link perlFunctionTag CFuncTag
```
They link to a few things in my rather heavily customized color scheme, but again that shouldn't affect anything. I'll look over the ignore code. Maybe there is something weird with classes. Also it might help to turn on the verbose debugging and see if anything looks weird there too.

**Comment by c0r73x** [comment]
I think I have found why. For some reason it creates one tag file per source file, when i look in my neotags_directory i got one for ```__src__.tags``` then ```__src__entry.cpp.tags``` and ```__src__entry.hpp.tags```.. and the ```__src__.tags``` file is empty :/

Not sure whats going on... I say we blame the gods!

*Edit:*
```File = os.path.realpath(self.__vim.api.eval("expand('%:p')"))``` Shouldn't this be expand('%:p:h') ?

*Edit 2:*
Oh! it was because i had recursive set to 0, but it's still strange. When using the_silver_searcher you shouldn't need to set the recursive flag to ctags, it should be handled by ag.

*Edit 3:*
Nvm. I saw that you said when recursive and find_tool is enabled it should use it. Maybe change it so that if find_tool is set it will always set the recursive as well?

But now it looks awesome :D

**Comment by c0r73x** [comment]
Oh, and the reason python highlight is missing is because of the containedin, if it's not set it wont override other highlights for some reason.

And that's what the notin variable does, it makes the highlighter ignore stuff like strings and comments.

**Comment by roflcopter4** [comment]
> Edit:
File = os.path.realpath(self.__vim.api.eval("expand('%:p')")) Shouldn't this be expand('%:p:h') ?

No, not in that case. When not acting recursively ctags only needs the absolute path of the file being edited, not the base directory.

> Edit 2:
Oh! it was because i had recursive set to 0, but it's still strange. When using the_silver_searcher you shouldn't need to set the recursive flag to ctags, it should be handled by ag.
Edit 3:
Nvm. I saw that you said when recursive and find_tool is enabled it should use it. Maybe change it so that if find_tool is set it will always set the recursive as well?

Hmm. What I figured was that people might have the find tool set and be able to just toggle recursive on and off for whatever reason if they needed to without changing it. If this way is confusing it should be easy to fix.

I added back the notin stuff (it was just commented out) and re-enabled the keyword stuff. I still don't really see the difference the notin makes though. Vim seems quite capable of not highlighting random stuff in comments as it is. I also never really noticed any overriding problems - actually in general I prefer that defaults *not* be overridden (hence all the ignore stuff I added), but that is kind of personal preference I suppose.

Assuming nothing else catches fire, there is one notable issue that is maybe not fixable. When I was messing around with EFL I originally had it re-evaluate the applicable tags every time the buffer changed. After about 3 seconds I realized how stupid that is; it is immensely too slow and distracting if you ever find yourself regularly switching buffers. The compromise I made was to have all tags in all loaded buffers be loaded, so there isn't so much calculating going on. The downside to this is that the whole point of ignoring tags starts to go away when you have lots of buffers open. Eventually tons of tags are loaded anyway.

And sometimes there is not winning at all. I checked the perl source code on a whim and to my dismay realized that the entire freaking interpreter is like 10 massive C files (the longest being 20000 lines). No way to avoid lots of tags if the whole project is crammed into a few files. 

In any case, assuming the recursion thing is working, what do you think of the whole "project" idea? Or ignoring all autoconf files? I was a bit concerned that one might annoy people.

**Comment by c0r73x** [comment]
I loved the ignore autoconf idea, I think that plus the keywords makes it possible to use neotags in the neovim source (before it was way to sluggish to be useful, at least with my settings).

Not sure about the project thing, I'm used to opening my files in the project root (at least I havn't had any issues with it). Might be because I store my tag files in a cache directory that gets wiped, also it's nice for me with the whole neovim_directory thing because I had similar setup in my vimrc but decided not to implement it for some reason :P. But I don't see any reason why it shouldn't be merged, if it helps people it's a good thing. And for those that don't like it they can just ignore it.

Anyhow I think we can merge this when the readme is fixed? Do you wan't to update the readme or should I merge it into dev and I can fix it when I have time to do so?

**Comment by roflcopter4** [comment]
I can take a stab at the readme. I actually tried to convert the thing to the vim help-file format before realizing I actually don't have any idea how to do that. I didn't realize they had their own unique format for some reason.

I'll see if I can make the readme make sense. It occurs to me that if this is merged it might break people's setup. I may need to see if I can avoid that too, but at the very least, since there's no way to push a changelog or something to people, there should be an up to date readme when they come here to complain.

**Comment by roflcopter4** [comment]
I updated quite  a bit of the readme and spent an embarrassingly long time converting it to a vim help file. Neither is perfect. And apparently there is a minor conflict with the readme. Doesn't look like anything too serious though.

Let me know what you think. 

EDIT: I also managed to speed things up a bit more by keeping a working cache of processed flags for each file. I just couldn't make this work by setting them as vim variables, but it does work fine with everything kept in the python code. This basically means only one buffer's tags are ever loaded in the editor at once, which is what I had hoped to achieve all along.

**Comment by c0r73x** [comment]
Hi, it looks really good :smiley: 

I think we can merge this? I've tested it and it seems to work perfectly, and I love the helpfile! :grin:

**Comment by c0r73x** [comment]
I merged it but I did found a tiny issue, NeotagsToggle seems to be broken :open_mouth: I will check why.

**Pull request merged**
